// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbrsvhfkxjxwhqoddhnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJicnN2aGZreGp4d2hxb2RkaG51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3MDkwOTcsImV4cCI6MjA3OTI4NTA5N30.2sFQbHoI9u7Vz-eLVZK9BM4CyX09cb-QDWRjb6TOFR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});