import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

const SUPABASE_URL = process.env.SUPABASE_URL || 'https://bbrsvhfkxjxwhqoddhnu.supabase.co';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJicnN2aGZreGp4d2hxb2RkaG51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3MDkwOTcsImV4cCI6MjA3OTI4NTA5N30.2sFQbHoI9u7Vz-eLVZK9BM4CyX09cb-QDWRjb6TOFR4';
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY; // For admin operations

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
export const supabaseAdmin = SUPABASE_SERVICE_KEY 
  ? createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY, {
      auth: {
        autoRefreshToken: false,
        persistSession: false
      }
    })
  : null;

/**
 * Get user by email (requires service role key for admin operations)
 */
export async function getUserByEmail(email) {
  if (!supabaseAdmin) {
    throw new Error('SUPABASE_SERVICE_KEY not configured. Cannot fetch user by email.');
  }
  
  const { data, error } = await supabaseAdmin.auth.admin.listUsers();
  if (error) throw error;
  
  const user = data.users.find(u => u.email?.toLowerCase() === email.toLowerCase());
  return user || null;
}

/**
 * Send Discord webhook notification
 */
export async function sendAccountGenerationWebhook(
  email,
  password,
  categoryName,
  generatorType,
  username,
  webhookUrl
) {
  try {
    const planEmoji = generatorType === 'vip' ? '👑' : '🎁';
    const planColor = generatorType === 'vip' ? 0xffd700 : 0x3498db;
    const successColor = 0x00ff00;

    const embed = {
      title: `✅ Account Generated Successfully!`,
      description: `**Category:** ${categoryName}\n**Account Email:** \`${email}\`\n\n${planEmoji} **${generatorType.toUpperCase()}** Generator - Successfully generated!`,
      color: successColor,
      fields: [
        {
          name: "👤 Generated By",
          value: username || "Discord User",
          inline: true,
        },
        {
          name: "📋 Plan",
          value: `${planEmoji} **${generatorType.toUpperCase()}**`,
          inline: true,
        },
        {
          name: "⏰ Generated At",
          value: `<t:${Math.floor(Date.now() / 1000)}:F>\n<t:${Math.floor(Date.now() / 1000)}:R>`,
          inline: false,
        },
      ],
      author: {
        name: "Acc Hub",
        icon_url: "https://cdn.discordapp.com/attachments/1441466120631488754/1441474372614492232/acchub.png",
      },
      footer: {
        text: "Acc Hub - Account Generator Platform",
        icon_url: "https://cdn.discordapp.com/attachments/1441466120631488754/1441474372614492232/acchub.png",
      },
      timestamp: new Date().toISOString(),
    };

    const payload = {
      embeds: [embed],
    };

    const response = await fetch(webhookUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      console.error('Discord webhook error:', response.status, response.statusText);
    }
  } catch (error) {
    console.error('Error sending Discord webhook:', error);
  }
}

